### ISSUE TITLE
[Layout] Add tabs for Spotify, YouTube and Apple so easier to navigate

### ISSUE THREAD

**Issue by gracekishino** [gracekishino/coding_playlists#4] opened 2023-11-30 07:29 UTC

**Comment by GarvAgarwal26** [comment] 2023-12-02 07:00
Hey, Can U please assign this issue to me, Not only this issue i want to help you with this whole project & I really liked your idea.

**Comment by GarvAgarwal26** [comment] 2023-12-02 08:59
Hey, can you specify to me how you want that button should be placed...like it will be great to work on your design :)

**Comment by gracekishino** [comment] 2023-12-02 09:04
@GarvAgarwal26 Thanks so much! That's amazing you'd like to help with the whole project too :)

I was thinking of putting the buttons at the top so they are easy to see for the user, perhaps something like this:
https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs

Does that make sense?

But feel free to do in any way you like and let me know if you need any help with the code or git and github!

Also, I sent you a collaborator invitation, I think that will give you a bit more access (I am new to GitHub so not sure how much, let me know if you can't access anything you need to). And If you have any ideas, etc please add issues for them.

**Comment by gracekishino** [comment] 2023-12-02 09:05
@GarvAgarwal26 if tabs are a bit complicated we could start with a separate html page each for youtube, spofity, etc and add in tabs later.

**Comment by GarvAgarwal26** [comment] 2023-12-02 20:46
Hey sorry for the late reply....it will be great to bootstrap the tabs and we will add further css if we need...is it okay?

Please let me know if you need any kind of help in this...I will be there 

And yeah as I said I like your idea I will open an issue if I think this change will be helpful for the project

And thanks for assigning:)

**Comment by Jainil2004** [comment] 2024-01-21 20:53
hi @gracekishino, if the issue is not resolved yet can I please be assigned? I would love to contribute.
thank you

**Comment by gracekishino** [comment] 2024-01-21 23:40
@SharkyBytes would you still like to work on this or would it be OK for @Jainil2004 to take this on?

**Comment by gracekishino** [comment] 2024-02-16 09:10
@SharkyBytes as it's been a month, I'll pass this on to @Jainil2004.

@Jainil2004 would you still like to work on this?

**Comment by Jainil2004** [comment] 2024-02-16 18:23
@gracekishino absolutely, I would love to work on this enhancement. just wanted to clarify things a little. The goal is to add tabs to sections (spotify, youtube, apple music) in the header right? if so I'll get it done on priority and will submit a PR asap. 
something like this:
![image](https://github.com/gracekishino/coding_playlists/assets/112818722/bf4fea23-dd62-4546-9c1b-9f31c143dfd1)

**Comment by gracekishino** [comment] 2024-02-17 08:54
@Jainil2004 I was thinking of tabs below the header, a bit like this: https://www.w3schools.com/w3css/w3css_tabulators.asp

But it might look better and save space with the links in the header as you suggested.

I'm flexible about how this is implemented (other than tabs it could be internal links to the sections on the page or even separate HTML pages). 

So please go with the method that you would like to work on and let me know if you have any questions or need any help!

**Comment by Jainil2004** [comment] 2024-02-17 14:44
@gracekishino sorry it took a while, but i have added the tab buttons for nav as requested and added other functionality, styling as well. please have a look at the PR I've explained in detail what are all the changes and how it all comes together in the end. Unfortunately, the contribution link is still on hold as I am not able to figure out a better place for it. so for now I have removed it. Also do provide me with feedback if anything needs to be changed. Thank you

**Comment by gracekishino** [comment] 2024-02-21 04:50
@Jainil2004 thanks so much for your contribution! You can see the changes live now: https://coding-playlists.netlify.app

**Closed** 2024-02-21 04:50 UTC
Labels: enhancement, good first issue
